// Web App Manifest — served at /manifest.webmanifest, auto-linked by
// Next.js. Provides standalone-app metadata (name, theme colour, icons)
// for Add-to-Home-Screen on Android + iOS and the install prompt on
// supporting desktop browsers.
//
// Icon srcs match the routes generated by app/icon.tsx (192x192) and
// app/icon1.tsx (512x512) — Next serves them at /icon and /icon1
// respectively as cached PNGs.
import type { MetadataRoute } from "next";

// Required under `output: 'export'` — emit a static manifest file.
export const dynamic = "force-static";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "AssetCentral",
    short_name: "AssetCentral",
    description: "AI agent team for property yield.",
    start_url: "/",
    display: "standalone",
    background_color: "#1a1a2e",
    theme_color: "#1a1a2e",
    icons: [
      { src: "/icon", sizes: "192x192", type: "image/png" },
      { src: "/icon1", sizes: "512x512", type: "image/png" },
    ],
  };
}
